text = input("Enter text:")
text1=text.strip()
print("Strip text: " + text1)
text2=text1.capitalize()
print("Capitalize text: " + text2)
text3=text2.title()
print("Title text: " + text3)
text4=text3.upper()
print("Upper text: " + text4)
text5=text4.lower()
print("Lower text: " + text5)